### ISSUE TITLE
需要英文文档的协助者

### ISSUE THREAD

**Issue by VergilGao** [VergilGao/vddswitcher#1]
我的英语真的很差

**Comment by qifeng2233** [comment]
# vddswitcher

A "just work" vdd program for streaming Sunshine.

Main features:

- Create a virtual display when starting the stream.

- Automatically set the resolution of the virtual display based on the resolution set in the Moonlight client (if supported).

- Close the virtual display when ending the stream.

## Usage

Make sure you have installed the following driver:

- [parsec-vdd-v0.41](https://builds.parsec.app/vdd/parsec-vdd-0.41.0.0.exe) 

Place `vddswitcher.exe` and `vddswitcherd.exe` in a location of your choice.

For the first use, configure the virtual desktop as the main display:

Right-click on the Start icon - Run - Enter `cmd`
In the opened command prompt, enter:

`cmd /C "path to vddswitcherd.exe" -x "your main display width in pixels" -y "your main display height in pixels" -r "your main display refresh rate"`

This will create a virtual display with the same resolution as your main display.

Go to the display configuration page and select the created virtual display, then check the option to set it as the main display. (Note: This will make your desktop look strange, but it can be restored)

You may find that you cannot see your mouse and some windows have been moved to the virtual display. In this case, it is more convenient to simply restart your computer.

After restarting your computer, you will find that the virtual display has disappeared.

Open Sunshine and go to `Configuration - General`.

In the "Do Command" field at the bottom, enter `cmd /C "path to vddswitcherd.exe" -x %SUNSHINE_CLIENT_WIDTH% -y %SUNSHINE_CLIENT_HEIGHT% -r %SUNSHINE_CLIENT_FPS%`

For example:

`cmd /C "D:\game\utils\vddswitcher\vddswitcherd.exe"  -x %SUNSHINE_CLIENT_WIDTH% -y %SUNSHINE_CLIENT_HEIGHT% -r %SUNSHINE_CLIENT_FPS%`

In the "Undo Command" field, enter `cmd /C "path to vddswitcher.exe"`

For example:

`cmd /C "D:\game\utils\vddswitcher\vddswitcher.exe"`

Save and apply the changes. Wait for the restart, then use Moonlight to enter the desktop.

Go to the display configuration page and disable any other displays outside of the virtual display to save energy.

## Supported Resolutions

| Resolution   | Common name      | Aspect ratio         | Refresh rates (Hz)
| -            | :-:              | :-:                  | :-:
| 4096 x 2160  | DCI 4K           | 1.90:1 (256:135)     | 24/30/60/144/240
| 3840 x 2160  | 4K UHD           | 16:9                 | 24/30/60/144/240
| 3840 x 1600  | UltraWide        | 24:10                | 24/30/60/144/240
| 3840 x 1080  | UltraWide        | 32:9 (2x 16:9 FHD)   | 24/30/60/144/240
| 3440 x 1440  |                  | 21.5:9 (43:18)       | 24/30/60/144/240
| 3240 x 2160  |                  | 3:2                  | 60
| 3200 x 1800  | 3K               | 16:9                 | 24/30/60/144/240
| 3000 x 2000  |                  | 3:2                  | 60
| 2880 x 1800  | 2.8K             | 16:10                | 60
| 2880 x 1620  | 2.8K             | 16:9                 | 24/30/60/144/240
| 2736 x 1824  |                  |                      | 60
| 2560 x 1600  | 2K               | 16:10                | 24/30/60/144/240
| 2560 x 1440  | 2K               | 16:9                 | 24/30/60/144/240
| 2560 x 1080  | UltraWide        | 21:9                 | 24/30/60/144/240
| 2496 x 1664  |                  |                      | 60
| 2256 x 1504  |                  |                      | 60
| 2048 x 1152  |                  |                      | 60/144/240
| 1920 x 1200  | FHD              | 16:10                | 60/144/240
|**1920 x 1080**| **FHD**         | **16:9**             | 24/30/**60**/144/240
| 1800 x 1200  | FHD              | 3:2                  | 60
| 1680 x 1050  | HD+              | 16:10                | 60/144/240
| 1600 x 1200  | HD+              | 4:3                  | 24/30/60/144/240
|  1600 x 900  | HD+              | 16:9                 | 60/144/240
|  1440 x 900  | HD               | 16:10                | 60/144/240
|  1366 x 768  |                  |                      | 60/144/240
|  1280 x 800  | HD               | 16:10                | 60/144/240
|  1280 x 720  | HD               | 16:9                 | 60/144/240

## Custom Resolutions

[parsec official website custom resolutions](https://support.parsec.app/hc/en-us/articles/4423615425293-VDD-Advanced-Configuration)

**Comment by qifeng2233** [comment]
直接给gpt喂文件的，看看有问题没
