### ISSUE TITLE
删除创建的显示器

### ISSUE THREAD

**Issue by univers629** [VergilGao/vddswitcher#12]
```
右键开始图标 - 运行 - 输入 cmd 在打开的 cmd 窗口中输入

cmd /C "vddswitcherd.exe的路径" -x "你的主显示器像素宽度" -y "你的主显示器像素高度" -r "你的主显示器刷新率"

此时将创建一个和你主显示器相同分辨率的虚拟显示器。
```

请问这一步怎么还原？，我想删除掉创建的这一个。

我之前在parsec-vdd上创建了一个2560x1600,120fps的虚拟现实器连接平板，在使用这个项目后，我按照说明创建了一个和电脑主显示器1920x1080,60fps相同的一个虚拟显示器，但是我发现在启动sunshine并不会自动创建虚拟显示器。而且当我用moonlinght连接时，这个创建的虚拟显示器会自动出现，让我之前创建的显示器从display2变成display3，并且输出名称也从\\.\DISPLAY9变成了\\.\DISPLAY10，导致我的moonlight无法连接。

我想删除掉按照说明创建的这个和电脑主显示器1920x1080,60fps相同的一个虚拟显示器，请问应该怎么做？
![image](https://github.com/user-attachments/assets/c1715c07-29b6-4279-91db-3cf6c9625ffb)

**Comment by VergilGao** [comment]
删掉 Do Command 栏 和 Undo Command 栏

**Comment by univers629** [comment]
> 删掉 Do Command 栏 和 Undo Command 栏

这样就行了嘛，这两部不是第二步和第三部吗？第一步创建一个相通分辨率吧的显示器会被删除吗，还是隐藏了？

**Comment by VergilGao** [comment]
> 
> 
> 
> > 删掉 Do Command 栏 和 Undo Command 栏
> 
> 这样就行了嘛，这两部不是第二步和第三部吗？第一步创建一个相通分辨率吧的显示器会被删除吗，还是隐藏了？

第一步是让你手动添加显示器这样方便你在本地计算机上管理当添加虚拟屏时的屏幕选项。
只要你 vddswitcherd 停了这个虚拟显示器就没了。
为了方便操作，直接重启就行。
