### ISSUE TITLE
Undo Command 栏填入 cmd /C "vddswitcher.exe的路径"后实际起作用是完全退出Sunshine吗？

### ISSUE THREAD

**Issue by f23258** [VergilGao/vddswitcher#13]
按照说明配置完了，目前进Moonlight能加载虚拟显示器，但要卸载的话仅关掉Moonling是不行的，得退出服务器端，有办法在Moonling退出的时候就完成卸载吗？

**Comment by VergilGao** [comment]
你关掉 Moonlight 前要结束串流

**Comment by f23258** [comment]
> 你关掉 Moonlight 前要结束串流

结束串流是指CTRL+ALT+SHIFT+Q吗？我执行这个操作的时候，虚拟显示器并没有卸载，完全退出Moonlight也不行，只有做了出去Sunshine的时候才出现卸载动作。

**Comment by f23258** [comment]
我是在MAC下用的MOONLIGHT的客户端。

**Comment by VergilGao** [comment]
我没太理解，你点那个停止键就是退出串流了啊。![Screenshot_2024-11-12-20-10-16-848_com.limelight.unofficialA.jpg](https://github.com/user-attachments/assets/48846a11-4c46-4955-9b6d-01d9801b0c39)

**Comment by f23258** [comment]
> 我没太理解，你点那个停止键就是退出串流了啊。

谢谢谢谢！我明白了，在MAC上它叫退出游戏。现在懂了，也知道怎么操作了，感谢，话题可以关闭。
