### ISSUE TITLE
能否支持使用 120hz 刷新率

### ISSUE THREAD

**Issue by fejich** [VergilGao/vddswitcher#2]
如题
24hz 没想到有什么用处，120hz 比较常见吧

**Comment by 472447831** [comment]
同希望加入120的支持，移动设备碍于限制最高只开放到4k120，如果采用4k144会重新采样（也许）

**Comment by VergilGao** [comment]
可以修改注册表来增加120hz
具体方案参考 https://support.parsec.app/hc/en-us/articles/4423615425293-VDD-Advanced-Configuration
