### ISSUE TITLE
如何自定义分辨率呢

### ISSUE THREAD

**Issue by TangXiaoLin-CN** [VergilGao/vddswitcher#3]
各种设备的分辨率大不相同，如何进行自定义呢

**Comment by macjohson** [comment]
[parsec官网自定义分辨率](https://support.parsec.app/hc/en-us/articles/4423615425293-VDD-Advanced-Configuration)
在注册表自定义分辨率就可以了，可以添加5个自定义的；启动虚拟显示器后，屏幕设置里面看一下虚拟显示器是否有你需要的分辨率，没有的话去注册表添加以下，关闭虚拟显示器再开启就好了。关闭虚拟显示器只需要到任务管理器把作者对应程序进程关闭就关闭了

**Comment by TangXiaoLin-CN** [comment]
欧克，找到了，感谢
