### ISSUE TITLE
创建虚拟显示器后，如何关闭或删除虚拟显示器？

### ISSUE THREAD

**Issue by hhmfs** [VergilGao/vddswitcher#6]
已通过vddswitcherd.exe创建虚拟显示器，请问如何删除呢？

**Comment by VergilGao** [comment]
运行 vddswitcher.exe

**Comment by Remawater** [comment]
> 运行 vddswitcher.exe


运行 vddswitcher.exe关闭的话 
 README 里 `Undo Command 栏填入 cmd /C "vddswitcherd.exe的路径"` 这里的vddswitcherd.exe写错了
